#pragma once
enum E_Items
{
	WEAPON_HANDGUN,
	WEAPON_SUBMACHINE,
	WEAPON_PLASTIC_EXPLOSIVE,
	WEAPON_REMOTE_MISSILE,
	WEAPON_MINE,
	WEAPON_GRENADE_LAUNCHER
};/*
  
  const char* ITEMS_LIST[] = {
	"HANDGUN",
	"SUBMACHINE",
	"PLASTIC_EXPLOSIVE",
	"REMOTE_MISSILE",
	"MINE",
	"GRENADE_LAUNCHER"
};*/
 
